### PR TITLE
New method reorder_fields()

### LINKED ISSUE #15: FR: Standardized order of entries
Makes a difference both in the printed manual, and also helps when editing the DESCRIPTION. Should be an option for writing, or a transformation of a description object

First draft:

1. Title
1. Description
1. Authors@R
1. Date
1. Version
1. License
1. BugReports, URL
1. Dependencies
1. LazyData, RoxygenNote, Encoding, etc.
1. Collate

Which fields have I missed?

### PR DESCRIPTION
**Pull request by krlmlr**
to manifest a sane order in the file. I decided against implementing an option in normalize(). If you like it, I'll work on a test and on a convenience argument to write(), and the non-oo API. (FWIW, we probably need a test that checks that each oo API has a non-oo counterpart.)

Fixes #15.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Very cool! I think we can hook it up to an option in `normalize()` as well.

**Comment by krlmlr** [comment]
An option would violate SRP, no?

**Comment by gaborcsardi** [comment]
YEs, I am wondering what the best way would be to hook it up with both `normalize()` and `write`. Ideally it should be possible to 1) get a nice order and 2) nice formatting with just a write call.

Maybe we can indeed leave normalize alone, and just add an option to write.

**Comment by krlmlr** [comment]
I'm having trouble adding the reorder_fields arg to idesc_write. It looks like this function doesn't use normalize() at all.

If it used normalize(), it would alter the state, same with reorder_fields(). I wonder if this is desired. Smells a bit, violates SRP again.

Why not simply say

```
description$new("DESCRIPTION") %$% reorder_fields() %$% normalize() %$% write()
```

and deprecate the normalize argument to write()? (I have no idea how magrittr does this, but it just works.)

**Comment by krlmlr** [comment]
PTAL, normalize arg is now removed from write().

**Comment by gaborcsardi** [comment]
Yes, `write()` does not call `normalize` because I don't want `write` to change the object.

To me `$write(normalize = TRUE)` means *write out a normalized DESCRIPTION file*, and not *first normalize it and then write it out*.

I think this is coming my reluctance of reformatting fields. I think reformatting fields is annoying, and if in doubt what I function should do, I just avoid it.

I agree with you that having a separate implementation is not really ideal. Maybe we should just `clone()` and then operate on the clone, both for `normalize` and `reorder_fields`. Or even by default for `write`.

Btw. having both `normalize` and `reorder_fields` is kinda heavy as well, it would be nice to have a single pretty-print option. E.g.

* if `normalize` is `TRUE`, do both
* if it is `fields`, or `order`, then just either.

How about something like this?

**Comment by krlmlr** [comment]
Beware: I got myself a copy of "Clean code" ;-)

I think the pipe-y architecture of all methods allows avoiding those special-behavior-triggering optional arguments:

```
description$new("DESCRIPTION")$reorder_fields()$normalize()$write()
description$new("DESCRIPTION")$clone()$reorder_fields()$normalize()$write()
description$new("DESCRIPTION")$normalize()$write()
```

Not too difficult to write, not much to ask of the user IMO.

What are the applications for writing a sanitized DESCRIPTION but continuing working on unsanitized data?

**Comment by gaborcsardi** [comment]
> Beware: I got myself a copy of "Clean code" ;-)

LOL.

> Not too difficult to write, not much to ask of the user IMO.

OK, that is pretty cool, actually. 

You are totally right, we can scrap the `normalize()` argument completely.

One last issue. How about including `reorder_fields()` in `normalize()`? I think that is reasonable, and you just need to remember a single function to sanitize `DESCRIPTION`. 

I think the people who do not care about formatting can just `normalize()` and the people who do, will write the file manually, anyway.

**Comment by gaborcsardi** [comment]
Btw. we can also call it `prettify` or `beautify`, maybe these are better than `normalize`.

**Comment by krlmlr** [comment]
normalize() is fine, but I guess this is the verb that does everything; the verb for reformatting values is now called reformat_values().

**Comment by krlmlr** [comment]
Still more to come.

**Comment by krlmlr** [comment]
I think this is ready now. Pity the Travis tests don't pass.

Non-OO API generation had to be adapted as well, was a user of normalize arg. Let me know if you want me to split/reorganize the PR. Summary:

- normalize() now also reorders fields
- new reformat_fields() and reorder_fields() allow more fine-grained normalization
- normalize argument to write() is gone
- tweaked default sort order of fields
- added missing argument available in idesc_str() but not in str() method

**Comment by gaborcsardi** [comment]
Cool! I think we can merge the whole thing and then sort out the details. 

I forgot what the deal was with the `screen`, etc arguments for the `str`, but I think I wanted colored printing on the screen, and no colors in the file, so I could not just use the output of `str`. Anyway, I think we can fix things up later.

**Comment by gaborcsardi** [comment]
Btw. I'll might remove the `Date` field from the list of "main" fields, I think it is bad practice to use it.

**Comment by krlmlr** [comment]
Without the Date field, automatic citation() doesn't seem to work.

Are we going to get a bump_version_to(version) method? This could also update the "Date" field.

**Comment by gaborcsardi** [comment]
Hmmm, I did not know that. Anyway, people can still add a date field, of course, and I guess if it is there it is better to put it in the front somewhere.

I suppose some bump_version method is appropriate, but people use different versioning systems, so I don't know if it is easy to come up with sg that is useful for many people.

**Comment by krlmlr** [comment]
Simple: let the user specify the target version, warn if new version is smaller.

**Comment by gaborcsardi** [comment]
Yeah, but they might as well edit the file then. Why would you load and use `description` for such a simple operation. Anyway, I don't think it is really important.

**Comment by krlmlr** [comment]
```
d$bump_version_to("0.1-2")
d$get("Version") %>% ensurer::ensure_that(. < "0.1-2") %$% set(Version = "0.1-2") %$% set(Date = as.character(Sys.Date())) # but only if Date field exists
```

Honestly, I like the first better ;-)

In my [use case](https://github.com/krlmlr/makeR/blob/5c56c09360927ec55a160401940c9b30b3700c7e/inst/gitflow/post-flow-release-start#L14-L17), I'd sure load the description package.

**Pull request merged**
